server:
  port: 8080
spring:
  application:
    name: divida-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: prod
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
  
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'