spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/controle_financeiro
    username: postgres
    password: postgres
