server:
  port: 8888
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/esley/config-server-properties
          search-paths:
          - 'contas*'
          default-label: master 

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

