server:
  port: 8888
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/esley/config-server-properties
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'